name: ForDjango

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Start ssh-agent
        run: eval $(ssh-agent) && ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY }}")

      - name: Add SSH private key to ssh-agent
        run: echo "$SSH_PRIVATE_KEY" | ssh-add -
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ec2-user/CICD_TEST
            git pull origin master
            python manage.py collectstatic --no-input
            python manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx