name: ForDjango

on:
  push:
    branches:
      - master

jobs:
  black: 
    name: Check Syntax with Black
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Black
        run: black .
    
  tests:
    name: Run Tests
    needs: black
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run Black
        run: python manage.py test

  deploy:
    name: Deploy Application
    needs: [black, tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ec2-user/CICD_TEST
            git pull origin master
            python manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx